header: {stamp: {sec: 0, nanosec: 0}, frame_id: ""}
joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
points:
#  - positions: [-1.57, 0.0, 0.0, 0.0, 0.0, 3.019]
#    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    time_from_start:
#      sec: 0
#      nanosec: 0
#  - positions: [-1.57, 0.447, 0.447, 0.0, 0.628, 3.019]
#    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    time_from_start:
#      sec: 20
#      nanosec: 0
#  - positions: [-1.57, 0.894, 0.894, 0.0, 0.942, 3.019]
#    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    time_from_start:
#      sec: 40
#      nanosec: 0
#  - positions: [-1.57, 1.34, 1.34, 0.0, 1.257, 3.019]
#    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    time_from_start:
#      sec: 60
#      nanosec: 0
#  - positions: [-1.57, 1.787, 1.787, 0.0, 1.57, 3.019]
#    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
#    time_from_start:
#      sec: 80
#      nanosec: 0
  - positions: [-1.57, 2.234, 2.234, 0.0, 1.57, 3.019]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 0
      nanosec: 0
  - positions: [-1.57, 1.916, 2.234, 0.0765, 1.595, 3.019]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 20
      nanosec: 0
  - positions: [-1.57, 1.916, 2.208, 0.0765, 1.595, 3.019]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 40
      nanosec: 0
  - positions: [-1.57, 1.916, 2.208, -0.0782, 1.595, 3.019]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 60
      nanosec: 0
  - positions: [-1.57, 1.916, 2.208, -0.233, 1.595, 3.019]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 80
      nanosec: 0

